name: Build and Release

on:
  push:
    branches:
    - develop

jobs:
  build:
    name: build release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18 # Specify the Go version

      - name: Build the project
        run: go build -o pixiedust

      - name: Archive the build
        run: tar -czf pixiedust.tar.gz pixiedust

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pixiedust
          path: pixiedust.tar.gz
